modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "more_rpg_classes"
version = "${version}"
displayName = "More RPG Library"
authors = "Fichte"
description = '''
Library with status effects, entity attributes & Spell engine API additions.
'''
#logoFile = ""

[[dependencies.more_rpg_classes]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.more_rpg_classes]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.more_rpg_classes]]
modId = "spell_engine"
type = "required"
versionRange = "[${spell_engine_version},)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config="more-rpg-classes.mixins.json"

[[mixins]]
config="more-rpg-classes-neoforge.mixins.json"
